#!/bin/bash

# docker init file. This will bring up all the services: celery, uwsgi, sshd, and nginx
service networking start
service nginx start
/usr/sbin/sshd
cd /home/docker/hydroshare
git pull
export PYTHONPATH=/home/docker/hydroshare
su docker -c "PYTHONPATH=/home/docker celery worker -A hydroshare -E -D"
uwsgi --ini /home/docker/hydroshare/uwsgi.ini
